### ISSUE TITLE
Сбор метрик в delivery service порождает исключения

### ISSUE THREAD

**Issue by shchuko** [shchuko/demo-service-181#112]
```
java.lang.IllegalArgumentException: Incorrect number of labels.
	at io.prometheus.client.SimpleCollector.labels(SimpleCollector.java:65)
	at com.itmo.microservices.shop.common.metrics.MetricCollector.passEvent(MetricCollector.java:70)
	at com.itmo.microservices.shop.delivery.impl.service.DefaultDeliveryService.handleStartDelivery(DefaultDeliveryService.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

```
https://github.com/shchuko/demo-service-181/blob/a984e232e1eb30d61f1ac371c09842887fdb4507/src/main/java/com/itmo/microservices/shop/delivery/impl/service/DefaultDeliveryService.java#L167

**Comment by shchuko** [comment]
Fxd
